import {MATCHED_ID, connectAccount, expect, fixtureState, providerState, test} from './app-fixture';
import {launchReview, openReview} from './review-setup';

test('inspects stored camera geometry offline without changing pending manual coordinates', async ({page, account}) => {
 test.setTimeout(90000);
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await expect(page.getByText('Succeeded · Location proposed', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 const before = (await providerState(page.request)).requests.length;
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort('failed'));
 await page.route('**/api/backend/ai/jobs/*/items/*/thumbnail', async route => route.fulfill({status: 404, body: '{}'}));
 await openReview(page);
 const map = page.getByRole('region', {name: 'Read-only proposal map'});
 await expect(page.getByText('Camera: 50, 14', {exact: true})).toBeVisible();
 await expect(page.getByText('Subject: 50.001, 14.001', {exact: true})).toBeVisible();
 await expect(page.getByText('Heading: 40° clockwise from true north', {exact: true})).toBeVisible();
 await expect(page.getByText(/Estimated radius: 250 m/)).toBeVisible();
 await expect(map.getByText(/Map tiles unavailable/)).toBeVisible();
 await expect(page.getByRole('region', {name: 'Saved result detail'}).getByText('Current image unavailable', {exact: true})).toBeVisible();
 await expect(map.locator('.ai-review-marker')).toHaveCount(2);
 await expect(map.locator('.leaflet-marker-draggable')).toHaveCount(0);
 const canvas = map.locator('.leaflet-container');
 await canvas.click({position: {x: 100, y: 100}});
 await canvas.click({button: 'right', position: {x: 150, y: 100}});
 const transfer = await page.evaluateHandle(() => new DataTransfer());
 await canvas.dispatchEvent('drop', {dataTransfer: transfer});
 const bounds = await canvas.boundingBox();
 expect(bounds).not.toBeNull();
 await page.mouse.move(bounds!.x + 100, bounds!.y + 180);
 await page.mouse.down(); await page.mouse.move(bounds!.x + 150, bounds!.y + 200); await page.mouse.up();
 await page.getByRole('tab', {name: 'en · Primary', exact: true}).focus();
 await page.keyboard.press('ArrowRight');
 await expect(page.getByRole('tab', {name: 'uk', exact: true})).toBeFocused();
 await expect(page.getByRole('tabpanel')).toContainText('Status: unavailable');
 await expect(page.getByRole('tabpanel')).toContainText('Synthetic translation unavailable.');
 await page.getByText('Evidence and limitations', {exact: true}).click();
 await expect(page.getByText('Model / visual evidence; no independent verification.', {exact: true})).toBeVisible();
 await page.screenshot({path: 'out/checks/ch15-apply/located-review.png'});
 await page.getByRole('button', {name: 'Back to results'}).click();
 await expect(page.locator('.ai-review-marker')).toHaveCount(0);
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 expect((await providerState(page.request)).requests.length).toBe(before);
 await page.getByRole('button', {name: 'Save Location', exact: true}).click();
 await expect.poll(async () => (await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], latitude: 52.25, longitude: 21.05}]);
});

test('inspects ambiguous alternatives by keyboard on a narrow screen without selecting or rewriting the result', async ({page, account}) => {
 test.setTimeout(60000);
 await connectAccount(page, account);
 await launchReview(page, 'review-ambiguous');
 await expect(page.getByText('Succeeded · Ambiguous location', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.setViewportSize({width: 390, height: 844});
 const before = (await providerState(page.request)).requests.length;
 await openReview(page);
 const analysis = new URL(page.url()).searchParams.get('aiResult');
 const original = await (await page.request.get(`/api/backend/ai/results/${analysis}`)).json();
 await expect(page.getByText('Viewing all alternatives. No candidate is approved.', {exact: true})).toBeVisible();
 await expect(page.locator('.ai-review-marker')).toHaveCount(4);
 const inspect = page.getByRole('button', {name: 'Inspect candidate candidate-2: Synthetic alternative viewpoint', exact: true});
 await inspect.focus(); await inspect.press('Enter');
 await expect(inspect).toHaveAttribute('aria-pressed', 'true');
 await expect(page.locator('.ai-review-marker')).toHaveCount(2);
 await expect(page.getByText('Description refers to candidate-1, not the currently inspected alternative.', {exact: true})).toBeVisible();
 await expect(page.getByRole('tabpanel')).toContainText('Synthetic example: a riverside walkway with a landmark in the distance.');
 const dialog = page.getByRole('dialog');
 expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch15-apply/ambiguous-mobile.png'});
 await page.getByRole('button', {name: 'Back to results'}).click();
 await expect(page.locator('.ai-review-marker')).toHaveCount(0);
 const row = page.getByRole('button', {name: /^Open result /}).first();
 await expect(row).toBeFocused(); await row.press('Enter');
 await expect(page.getByText('Viewing all alternatives. No candidate is approved.', {exact: true})).toBeVisible();
 expect(await (await page.request.get(`/api/backend/ai/results/${analysis}`)).json()).toEqual(original);
 expect((await providerState(page.request)).requests.length).toBe(before);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await expect(page.locator('.ai-review-marker')).toHaveCount(0);
 await expect(page.getByRole('button', {name: 'AI Results', exact: true})).toBeFocused();
});

test('reviews Research estimates and references by keyboard on a narrow offline map without writes', async ({page, account}) => {
 test.setTimeout(60000);
 await connectAccount(page, account);
 await launchReview(page, 'research-ambiguous', 'research');
 await expect(page.getByText('Succeeded · Ambiguous location', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.setViewportSize({width:390,height:844});
 const before=(await providerState(page.request)).requests.length;
 const referenceRequests:string[]=[];
 await page.route('https://example.org/**',async route=>{referenceRequests.push(route.request().url());await route.abort();});
 await page.route('https://*.basemaps.cartocdn.com/**',async route=>route.abort());
 await openReview(page);
 const inspect=page.getByRole('button',{name:'Inspect candidate candidate-2: Synthetic alternative viewpoint',exact:true});
 await inspect.focus();await inspect.press('Enter');
 await expect(page.getByText('Camera: 51, 15',{exact:true})).toBeVisible();
 await expect(page.getByText('Estimated error: ±5 km',{exact:true})).toHaveCount(2);
 await expect(page.getByText('Estimated error: ±5 km',{exact:true}).nth(1)).toBeVisible();
 await expect(page.getByRole('link',{name:'Public reference',exact:true})).toHaveAttribute('href','https://example.org/reference');
 const dialog=page.getByRole('dialog');
 expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true);
 expect(referenceRequests).toEqual([]);
 expect((await providerState(page.request)).requests.length).toBe(before);
 expect((await fixtureState(page.request,account.key)).writes).toEqual([]);
 await page.screenshot({path:'out/checks/research-review-mobile.png'});
});

test('persists local drafts, reconciles two tabs and reviews baselines without upstream writes', async ({page, context, account}) => {
 test.setTimeout(90000);
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await expect(page.getByText('Saved draft · Revision 1', {exact: true})).toBeVisible();
 const second = await context.newPage();
 const blockedSecond: string[] = [];
 await second.route('**/*', async route => {
  const url = new URL(route.request().url());
  if (url.origin === 'http://127.0.0.1:3080') {await route.continue(); return;}
  if (!/^[abc]\.basemaps\.cartocdn\.com$/.test(url.hostname)) {blockedSecond.push(url.origin);}
  await route.abort();
 });
 await second.goto(page.url());
 await expect(second.getByText('Saved draft · Revision 1', {exact: true})).toBeVisible();
 await second.getByLabel('Camera latitude', {exact: true}).fill('7');
 await second.getByLabel('Camera longitude', {exact: true}).fill('8');
 const lat = page.getByLabel('Camera latitude', {exact: true});
 await lat.focus(); await lat.fill('0'); await lat.press('Tab');
 await page.getByLabel('Camera longitude', {exact: true}).fill('0');
 await page.getByLabel('Select GPS for this photo', {exact: true}).check();
 await page.getByRole('button', {name: 'Stage GPS draft'}).press('Enter');
 await expect(page.getByText('Saved staged · Revision 2', {exact: true})).toBeVisible();
 await expect(page.getByText('Heading: needs review', {exact: true})).toBeVisible();
 await second.getByRole('button', {name: 'Save draft', exact: true}).click();
 await expect(second.getByText(/Another tab saved/)).toBeVisible();
 await expect(second.getByLabel('Camera latitude', {exact: true})).toHaveValue('7');
 await second.getByRole('button', {name: 'Compare saved revision'}).click();
 await expect(second.getByText('Saved elsewhere: revision 2 · Camera 0, 0', {exact: true})).toBeVisible();
 await second.getByRole('button', {name: 'Discard edits and use saved revision'}).click();
 await expect(second.getByLabel('Camera latitude', {exact: true})).toHaveValue('0');
 expect(blockedSecond).toEqual([]);
 await second.close();
 await page.getByLabel('Heading degrees', {exact: true}).fill('0');
 await page.getByRole('button', {name: 'Save draft', exact: true}).click();
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and GPS'}).click();
 await expect(page.getByText('Observed GPS: latitude absent · longitude absent', {exact: true})).toBeVisible();
 await page.getByLabel('I reviewed this current image and its displayed GPS').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).click();
 await expect(page.getByText('Saved draft · Revision 4', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Reject draft'}).click();
 await expect(page.getByText('Saved rejected · Revision 5', {exact: true})).toBeVisible();
 await page.reload();
 await expect(page.getByText('Saved rejected · Revision 5', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Reopen draft'}).click();
 await expect(page.getByText('Saved draft · Revision 6', {exact: true})).toBeVisible();
 const dialog = page.getByRole('dialog');
 expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch16/draft-mobile.png'});
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
});

test('keeps manual pending coordinates isolated and asks before discarding unsaved AI edits', async ({page, account}) => {
 test.setTimeout(60000);
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await expect(page.getByText('Saved draft · Revision 1', {exact: true})).toBeVisible();
 await page.getByLabel('Select GPS for this photo').check();
 await expect(page.getByRole('button', {name: 'Stage GPS draft'})).toBeDisabled();
 await expect(page.getByText(/A manual location is pending for this photo/)).toBeVisible();
 await page.getByLabel('Camera latitude', {exact: true}).fill('0');
 await page.getByRole('button', {name: 'Back to results'}).click();
 await page.getByRole('button', {name: 'Keep editing', exact: true}).click();
 await expect(page.getByLabel('Camera latitude', {exact: true})).toHaveValue('0');
 await page.getByRole('button', {name: 'Save draft', exact: true}).click();
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByLabel('Camera latitude', {exact: true}).fill('9');
 await page.getByRole('button', {name: 'Back to results'}).click();
 await page.getByRole('button', {name: 'Discard unsaved edits', exact: true}).click();
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 expect((await providerState(page.request)).requests.length).toBe(calls);
 await page.getByRole('button', {name: 'Save Location', exact: true}).click();
 await expect.poll(async () => (await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], latitude: 52.25, longitude: 21.05}]);
});
