import {connectAccount, expect, fixtureState, providerState, test} from './app-fixture';

test('launches a durable Visual job, restores progress and creates a separately consented Context reanalysis', async ({page, account}) => {
 test.setTimeout(90000);
 await connectAccount(page, account);
 await page.getByRole('button', {name: 'Settings', exact: true}).click();
 await page.getByRole('button', {name: 'AI providers', exact: true}).click();
 await page.getByRole('button', {name: 'Create provider'}).click();
 await page.getByLabel('Name', {exact: true}).fill('Batch synthetic');
 await page.getByLabel('API base URL', {exact: true}).fill('http://127.0.0.1:8090/v1');
 await page.getByLabel('Model', {exact: true}).fill('manual-model');
 await page.getByLabel('API key', {exact: true}).fill('synthetic-batch-secret');
 await page.getByRole('button', {name: 'Save provider'}).click();
 await expect(page.getByText('Saved revision 1', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Test provider'}).click();
 await expect(page.getByText(/Strict: supported/i)).toBeVisible({timeout: 45000});
 const me = await (await page.request.get('/api/backend/auth/me')).json();
 const profiles = await (await page.request.get('/api/backend/ai/providers')).json();
 const configured = await page.request.post('http://127.0.0.1:8091/configure', {data: {owner: me.user.ID, profile: profiles.items[0].id}});
 expect(await configured.text()).toBe('{"ready":true}');
 expect(configured.ok()).toBe(true);
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.getByRole('button', {name: 'AI Locate', exact: true}).click();
 await page.getByRole('button', {name: 'Preview all matching assets'}).click();
 await expect(page.getByText(/Eligible: 2/)).toBeVisible();
 await page.getByRole('checkbox', {name: /I consent/}).check();
 await page.getByRole('button', {name: 'Preview current page'}).click();
 await expect(page.getByText(/Eligible: 2/)).toBeVisible();
 const consent = page.getByRole('checkbox', {name: /I consent/});
 await expect(consent).not.toBeChecked();
 let didLoseAcknowledgement = false;
 const submissionKeys: string[] = [];
 await page.route('**/api/backend/ai/jobs', async route => {
  if (route.request().method() === 'POST') {
   submissionKeys.push(route.request().postDataJSON().idempotencyKey);
   if (!didLoseAcknowledgement) {
    didLoseAcknowledgement = true;
    await route.fetch(); await route.abort('failed'); return;
   }
  }
  await route.continue();
 });
 await consent.check();
 await page.getByRole('button', {name: 'Start analysis', exact: true}).click();
 await page.getByRole('button', {name: 'Reconcile submission'}).click();
 expect(submissionKeys).toHaveLength(2);
 expect(submissionKeys[1]).toBe(submissionKeys[0]);
 await expect(page.getByText('Job complete', {exact: true})).toBeVisible({timeout: 15000});
 await expect(page.getByText('Succeeded · Location unknown', {exact: true})).toHaveCount(2);
 const parent = new URL(page.url()).searchParams.get('aiJob');
 expect(parent).toBeTruthy();
 const parentBefore = await (await page.request.get(`/api/backend/ai/jobs/${parent}`)).json();
 await page.reload();
 await expect(page.getByText(`Job ${parent}`, {exact: true})).toBeVisible();
 await page.getByRole('checkbox', {name: 'Reanalyze 11111111-1111-4111-8111-111111111111'}).check();
 await page.getByRole('button', {name: 'Preview reanalysis of selected assets'}).click();
 await page.getByRole('button', {name: 'Preview selected assets'}).click();
 await page.getByLabel('Analysis mode', {exact: true}).selectOption('context-assisted');
 await expect(page.getByRole('checkbox', {name: 'Capture time', exact: true})).not.toBeChecked();
 await page.getByRole('checkbox', {name: 'User hint', exact: true}).check();
 await page.getByLabel('Hint', {exact: true}).fill('Synthetic context hint');
 await expect(consent).not.toBeChecked();
 await consent.check();
 await page.getByRole('button', {name: 'Start analysis', exact: true}).click();
 await expect(page.getByText('Job complete', {exact: true})).toBeVisible({timeout: 15000});
 await expect(page.getByText('Succeeded · Location unknown', {exact: true})).toHaveCount(1);
 const child = new URL(page.url()).searchParams.get('aiJob');
 expect(child).not.toBe(parent);
 const childData = await (await page.request.get(`/api/backend/ai/jobs/${child}`)).json();
 expect(childData.configuration.rerun).toEqual({parentJobId: parent, kind: 'reanalysis'});
 await page.screenshot({path: 'out/checks/ch13-apply/context-progress.png'});
 expect(await (await page.request.get(`/api/backend/ai/jobs/${parent}`)).json()).toEqual(parentBefore);
 const attempts = (await providerState(page.request)).requests.filter(entry => entry.analysis);
 expect(attempts).toHaveLength(3);
 expect(attempts.filter(entry => entry.contextHintIncluded)).toHaveLength(1);
 const disabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {enabled: false}});
 expect(disabled.ok()).toBe(true);
 await page.reload();
 await expect(page.getByText(`Job ${child}`, {exact: true})).toBeVisible();
 await expect(page.getByText('Succeeded · Location unknown', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 await page.request.post('http://127.0.0.1:8091/configure', {data: {enabled: true}});
});

test('keyboard users can preview, authorize and cancel mixed work without losing completed results', async ({page, account}) => {
 test.setTimeout(60000);
 await connectAccount(page, account);
 await page.getByRole('button', {name: 'Settings', exact: true}).click();
 await page.getByRole('button', {name: 'AI providers', exact: true}).click();
 await page.getByRole('button', {name: 'Create provider'}).click();
 await page.getByLabel('Name', {exact: true}).fill('Keyboard synthetic');
 await page.getByLabel('API base URL', {exact: true}).fill('http://127.0.0.1:8090/v1');
 await page.getByLabel('Model', {exact: true}).fill('delayed-second-analysis');
 await page.getByLabel('API key', {exact: true}).fill('synthetic-keyboard-secret');
 await page.getByRole('button', {name: 'Save provider'}).click();
 await expect(page.getByText('Saved revision 1', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Test provider'}).click();
 await expect(page.getByText(/Strict: supported/i)).toBeVisible({timeout: 45000});
 const me = await (await page.request.get('/api/backend/auth/me')).json();
 const profiles = await (await page.request.get('/api/backend/ai/providers')).json();
 const configured = await page.request.post('http://127.0.0.1:8091/configure', {data: {owner: me.user.ID, profile: profiles.items[0].id}});
 expect(configured.ok()).toBe(true);
 await page.getByRole('button', {name: 'Close dialog'}).click();
 const entry = page.getByRole('button', {name: 'AI Locate', exact: true});
 await entry.focus(); await entry.press('Enter');
 await expect(page.getByRole('button', {name: 'Close dialog'})).toBeFocused();
 const preview = page.getByRole('button', {name: 'Preview current page'});
 await expect(preview).toBeEnabled();
 for (let step = 0; step < 4; step++) {await page.keyboard.press('Tab');}
 await expect(preview).toBeFocused(); await page.keyboard.press('Enter');
 await expect(page.getByText(/Eligible: 2/)).toBeVisible();
 const consent = page.getByRole('checkbox', {name: /I consent/});
 await consent.focus(); await consent.press('Space');
 await page.keyboard.press('Tab');
 const start = page.getByRole('button', {name: 'Start analysis', exact: true});
 await expect(start).toBeFocused(); await page.keyboard.press('Enter');
 await expect(page.getByText('Succeeded · Location unknown', {exact: true})).toHaveCount(1);
 const cancel = page.getByRole('button', {name: 'Cancel remaining work'});
 await cancel.focus(); await cancel.press('Enter');
 await expect(page.getByText('Cancellation requested', {exact: true})).toBeVisible();
 await expect(page.getByText('Canceled', {exact: true})).toHaveCount(1);
 await expect(page.getByText('Succeeded · Location unknown', {exact: true})).toHaveCount(1);
 const id = new URL(page.url()).searchParams.get('aiJob');
 const again = await page.request.post(`/api/backend/ai/jobs/${id}/cancel`, {headers: {Origin: 'http://127.0.0.1:3080'}, data: {}});
 expect(again.ok()).toBe(true);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 const requests = (await providerState(page.request)).requests.filter(entry => entry.model === 'delayed-second-analysis');
 expect(requests).toHaveLength(5);
});
