import {MATCHED_ID, UNMATCHED_ID, connectAccount, expect, fixtureState, photo, providerState, test} from './app-fixture';
import {launchReview, openReview} from './review-setup';

test('confirms an exact stack subset by keyboard and retains partial target history without consuming manual GPS', async ({page, account}) => {
 test.setTimeout(90000);
 const sibling = '33333333-3333-4333-8333-333333333333';
 const rejected = '44444444-4444-4444-8444-444444444444';
	const prepared = await page.request.post('http://127.0.0.1:8090/__stack_fixture', {headers: Object.fromEntries([['x-api-key', account.key]]), data: {rejectAsset: rejected}});
 expect(prepared.ok()).toBe(true);
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await photo(page, UNMATCHED_ID).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 const enabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: true, stackEnabled: true, disposableFixture: 'synthetic-stack-targets-v3'}});
 expect(enabled.ok()).toBe(true);
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await page.getByLabel('Camera latitude', {exact: true}).fill('0');
 await page.getByLabel('Camera longitude', {exact: true}).fill('12');
 await page.getByLabel('Select GPS for this photo').check();
 await page.getByRole('button', {name: 'Save draft', exact: true}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and GPS'}).press('Enter');
 await page.getByLabel('I reviewed this current image and its displayed GPS').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Stage GPS draft'}).press('Enter');
 await expect(page.getByText('Saved staged · Revision 4', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review stack members', exact: true}).press('Enter');
 await expect(page.getByRole('checkbox', {name: `Include photo ${MATCHED_ID}`, exact: true})).toBeChecked();
 await expect(page.getByRole('checkbox', {name: `Include photo ${sibling}`, exact: true})).not.toBeChecked();
 for (const asset of [sibling, rejected]) {
  const selected = page.getByRole('checkbox', {name: `Include photo ${asset}`, exact: true});
  await selected.focus(); await selected.press('Space');
 }
 await page.getByRole('button', {name: 'Read selected target baselines'}).press('Enter');
 for (const asset of [MATCHED_ID, sibling, rejected]) {
  const reviewed = page.getByRole('checkbox', {name: `Reviewed source and GPS for ${asset}`, exact: true});
  await reviewed.focus(); await reviewed.press('Space');
 }
 await page.getByRole('button', {name: 'Preview exact GPS'}).press('Enter');
 const matrix = page.getByRole('region', {name: 'Approved stack target matrix', exact: true});
 await expect(matrix).toBeVisible();
 await expect(matrix.getByRole('region', {name: /^Approved photo /})).toHaveCount(3);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 await page.getByRole('button', {name: 'Confirm GPS write'}).press('Enter');
 await expect(page.getByRole('region', {name: `Outcome for ${MATCHED_ID}`, exact: true}).getByText('Target status: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByRole('region', {name: `Outcome for ${sibling}`, exact: true}).getByText('Target status: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByRole('region', {name: `Outcome for ${rejected}`, exact: true}).getByText('Target status: retryable', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toEqual([MATCHED_ID, sibling, rejected].map(asset => ({ids: [asset], latitude: 0, longitude: 12})));
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch21/stack-mobile.png'});
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.setViewportSize({width: 1440, height: 1000});
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await openReview(page);
 expect((await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: false}})).ok()).toBe(true);
 await page.reload();
 await expect(page.getByRole('region', {name: `Outcome for ${rejected}`, exact: true}).getByText('Target status: retryable', {exact: true})).toBeVisible();
 await expect(page.getByRole('region', {name: `Outcome for ${sibling}`, exact: true}).getByText('Target status: succeeded', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toHaveLength(3);
});

test('confirms exact GPS by keyboard, reconciles a lost acknowledgement and retains history after verified catalog refresh', async ({page, account}) => {
 test.setTimeout(90000);
 await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', {value: undefined}));
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await photo(page, UNMATCHED_ID).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await page.getByLabel('Camera latitude', {exact: true}).fill('0');
 await page.getByLabel('Camera longitude', {exact: true}).fill('12');
 await page.getByLabel('Select GPS for this photo').check();
 await page.getByRole('button', {name: 'Save draft', exact: true}).click();
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and GPS'}).click();
 await page.getByLabel('I reviewed this current image and its displayed GPS').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).click();
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Stage GPS draft'}).click();
 await expect(page.getByText('Saved staged · Revision 4', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Preview exact GPS'}).click();
 await expect(page.getByLabel('Proposed latitude')).toHaveValue('0');
 await expect(page.getByLabel('Proposed longitude')).toHaveValue('12');
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 const enabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: true, disposableFixture: 'synthetic-gps-only-v1'}});
 expect(enabled.ok()).toBe(true);
 const confirmations: string[] = [];
 await page.route('**/api/backend/ai/write-operations', async route => {
  if (route.request().method() !== 'POST') {await route.continue(); return;}
  confirmations.push(route.request().postData() || '');
  await route.fetch(); await route.abort('failed');
 });
 const confirm = page.getByRole('button', {name: 'Confirm GPS write'});
 await confirm.focus(); await confirm.press('Enter');
 await expect(page.getByText(/Confirmation acknowledgement unavailable/)).toBeVisible();
 await page.getByRole('button', {name: 'Reconcile confirmation'}).press('Enter');
 await expect(page.getByText('GPS operation: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByText(/GPS verified and local catalog updated/)).toBeVisible();
 await expect(page.getByText(`Approved revision 4 · Photo ${MATCHED_ID}`, {exact: true})).toBeVisible();
 await expect(page.getByText('Observed GPS: 0, 12', {exact: true})).toBeVisible();
 expect(confirmations).toHaveLength(1);
 expect(JSON.parse(confirmations[0]).idempotencyKey).toMatch(/^[a-f0-9]{32}$/);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], latitude: 0, longitude: 12}]);
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch19/write-mobile.png'});
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await expect(photo(page, MATCHED_ID)).toHaveCount(0);
 await page.setViewportSize({width: 1440, height: 1000});
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await openReview(page);
 const disabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: false}});
 expect(disabled.ok()).toBe(true);
 await page.reload();
 await expect(page.getByText('GPS operation: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByText('Approved intended: 0, 12', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toHaveLength(1);
 expect((await providerState(page.request)).requests.length).toBe(calls);
});

test('writes an exact description by keyboard without consuming pending GPS or Missing GPS membership', async ({page, account}) => {
 test.setTimeout(90000);
 const description = 'An exact e\u0301 scene.\nSecond line with <literal text> and trailing spaces  ';
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 const enabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: true, descriptionEnabled: true, disposableFixture: 'synthetic-standard-fields-v2'}});
 expect(enabled.ok()).toBe(true);
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await page.getByLabel('Camera latitude', {exact: true}).fill('');
 await page.getByLabel('Camera longitude', {exact: true}).fill('');
 await page.getByRole('textbox', {name: 'Description en', exact: true}).fill(description);
 await page.getByLabel('Primary description language').selectOption('en');
 await page.getByLabel('Description policy').selectOption('replace');
 await page.getByLabel('Select description for this photo').check();
 await page.getByRole('button', {name: 'Save draft', exact: true}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and selected fields'}).press('Enter');
 await page.getByLabel('I reviewed this current image and its displayed selected fields').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Stage selected fields'}).press('Enter');
 await expect(page.getByText('Saved staged · Revision 4', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Preview selected fields'}).press('Enter');
 await expect(page.getByText('Preview status: usable', {exact: true})).toBeVisible();
 expect(await page.getByLabel('Before description', {exact: true}).textContent()).toBe('');
 expect(await page.getByLabel('Proposed description', {exact: true}).textContent()).toBe(description);
 await expect(page.getByLabel('Proposed latitude', {exact: true})).toHaveCount(0);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 await page.getByRole('button', {name: 'Confirm selected fields write'}).press('Enter');
 await expect(page.getByText('Selected fields operation: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByText('Description: verified', {exact: true})).toBeVisible();
 await expect(page.getByText('Description verified; no GPS catalog refresh is needed.', {exact: true})).toBeVisible();
 expect(await page.getByLabel('Observed description', {exact: true}).textContent()).toBe(description);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], description}]);
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch20/description-mobile.png'});
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.setViewportSize({width: 1440, height: 1000});
 await expect(photo(page, MATCHED_ID)).toBeVisible();
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await openReview(page);
 const disabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: false}});
 expect(disabled.ok()).toBe(true);
 await page.reload();
 await expect(page.getByText('Selected fields operation: succeeded', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toHaveLength(1);
});

test('keeps description success and manual GPS while retrying only optional metadata by keyboard', async ({page, account}) => {
 test.setTimeout(90000);
 const description = 'Reviewed e\u0301 scene.\nExact shared text  ';
 const prepared = await page.request.post('http://127.0.0.1:8090/__mirror_fixture', {headers: Object.fromEntries([['x-api-key', account.key]]), data: {assetId: MATCHED_ID, rejectOnce: true}});
 expect(prepared.ok()).toBe(true);
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 const enabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: true, descriptionEnabled: true, metadataEnabled: true, disposableFixture: 'synthetic-metadata-v4'}});
 expect(enabled.ok()).toBe(true);
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await page.getByLabel('Camera latitude', {exact: true}).fill('');
 await page.getByLabel('Camera longitude', {exact: true}).fill('');
 await page.getByRole('textbox', {name: 'Description en', exact: true}).fill(description);
 await page.getByLabel('Primary description language').selectOption('en');
 await page.getByLabel('Description policy').selectOption('replace');
 await page.getByLabel('Select description for this photo').check();
 await page.getByLabel('Mirror optional metadata for this photo', {exact: true}).check();
 await page.getByLabel('Mirror description en', {exact: true}).check();
 await page.getByRole('button', {name: 'Save draft', exact: true}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and selected fields'}).press('Enter');
 await page.getByLabel('I reviewed this current image and its displayed selected fields').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).press('Enter');
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Stage selected fields'}).press('Enter');
 await expect(page.getByText('Saved staged · Revision 4', {exact: true})).toBeVisible();
 await page.getByLabel('I understand authorized asset readers may see this exported information').check();
 await page.getByRole('button', {name: 'Preview selected fields'}).press('Enter');
 await expect(page.getByText('Preview status: usable', {exact: true})).toBeVisible();
 await page.getByText('Exact metadata before and after', {exact: true}).click();
 const exported = JSON.parse(await page.getByLabel('Proposed metadata', {exact: true}).textContent() || '{}');
 expect(exported.descriptions).toEqual({en: description});
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 await page.getByRole('button', {name: 'Confirm selected fields write'}).press('Enter');
 const mirror = page.getByRole('region', {name: 'Metadata step outcome', exact: true});
 await expect(mirror.getByRole('button', {name: 'Retry metadata only', exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], description}]);
 await expect(page.getByRole('textbox', {name: 'Description en', exact: true})).toHaveValue(description);
 await mirror.getByRole('button', {name: 'Retry metadata only', exact: true}).press('Enter');
 await expect(mirror.getByText(/succeeded/, {exact: false}).first()).toBeVisible();
 const stateResponse = await page.request.get(`http://127.0.0.1:8090/__state/${account.key}`);
 const state = await stateResponse.json();
 expect(state.metadataWrites).toHaveLength(2);
 expect(state.metadataWrites[0]).toEqual(state.metadataWrites[1]);
 expect(state.metadata[MATCHED_ID]).toEqual([{key: 'unrelated-fixture', value: {keep: true}}, {key: 'immich-places-ai-addon', value: exported}]);
 expect(state.metadata[UNMATCHED_ID]).toEqual([{key: 'unrelated-fixture', value: {keep: true}}]);
 expect(state.writes).toEqual([{ids: [MATCHED_ID], description}]);
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch22/metadata-mobile.png'});
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await page.setViewportSize({width: 1440, height: 1000});
 await expect(photo(page, MATCHED_ID)).toBeVisible();
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await openReview(page);
 expect((await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: false}})).ok()).toBe(true);
 await page.reload();
 await expect(page.getByRole('region', {name: 'Metadata step outcome', exact: true}).getByText(/succeeded/).first()).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toHaveLength(1);
});
