import {MATCHED_ID, UNMATCHED_ID, connectAccount, expect, fixtureState, photo, providerState, test} from './app-fixture';
import {launchReview, openReview} from './review-setup';

test('confirms exact GPS by keyboard, reconciles a lost acknowledgement and retains history after verified catalog refresh', async ({page, account}) => {
 test.setTimeout(90000);
 await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', {value: undefined}));
 await connectAccount(page, account);
 await launchReview(page, 'review-located');
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await photo(page, UNMATCHED_ID).click();
 await page.getByPlaceholder('Search location').fill('52.25, 21.05');
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await page.route('https://*.basemaps.cartocdn.com/**', async route => route.abort());
 await page.setViewportSize({width: 390, height: 844});
 const calls = (await providerState(page.request)).requests.length;
 await openReview(page);
 await page.getByRole('button', {name: 'Accept as local draft'}).click();
 await page.getByLabel('Camera latitude', {exact: true}).fill('0');
 await page.getByLabel('Camera longitude', {exact: true}).fill('12');
 await page.getByLabel('Select GPS for this photo').check();
 await page.getByRole('button', {name: 'Save draft', exact: true}).click();
 await expect(page.getByText('Saved draft · Revision 2', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Review current source and GPS'}).click();
 await page.getByLabel('I reviewed this current image and its displayed GPS').check();
 await page.getByRole('button', {name: 'Acknowledge displayed baseline'}).click();
 await expect(page.getByText('Saved draft · Revision 3', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Stage GPS draft'}).click();
 await expect(page.getByText('Saved staged · Revision 4', {exact: true})).toBeVisible();
 await page.getByRole('button', {name: 'Preview exact GPS'}).click();
 await expect(page.getByLabel('Proposed latitude')).toHaveValue('0');
 await expect(page.getByLabel('Proposed longitude')).toHaveValue('12');
 expect((await fixtureState(page.request, account.key)).writes).toEqual([]);
 const enabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: true, disposableFixture: 'synthetic-gps-only-v1'}});
 expect(enabled.ok()).toBe(true);
 const confirmations: string[] = [];
 await page.route('**/api/backend/ai/write-operations', async route => {
  if (route.request().method() !== 'POST') {await route.continue(); return;}
  confirmations.push(route.request().postData() || '');
  await route.fetch(); await route.abort('failed');
 });
 const confirm = page.getByRole('button', {name: 'Confirm GPS write'});
 await confirm.focus(); await confirm.press('Enter');
 await expect(page.getByText(/Confirmation acknowledgement unavailable/)).toBeVisible();
 await page.getByRole('button', {name: 'Reconcile confirmation'}).press('Enter');
 await expect(page.getByText('GPS operation: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByText(/GPS verified and local catalog updated/)).toBeVisible();
 await expect(page.getByText(`Approved revision 4 · Photo ${MATCHED_ID}`, {exact: true})).toBeVisible();
 await expect(page.getByText('Observed GPS: 0, 12', {exact: true})).toBeVisible();
 expect(confirmations).toHaveLength(1);
 expect(JSON.parse(confirmations[0]).idempotencyKey).toMatch(/^[a-f0-9]{32}$/);
 expect((await fixtureState(page.request, account.key)).writes).toEqual([{ids: [MATCHED_ID], latitude: 0, longitude: 12}]);
 expect((await providerState(page.request)).requests.length).toBe(calls);
 expect(await page.getByRole('dialog').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
 await page.screenshot({path: 'out/checks/ch19/write-mobile.png'});
 await page.getByRole('button', {name: 'Close dialog'}).click();
 await expect(photo(page, MATCHED_ID)).toHaveCount(0);
 await page.setViewportSize({width: 1440, height: 1000});
 await expect(page.getByText('1 edited image', {exact: true})).toBeVisible();
 await openReview(page);
 const disabled = await page.request.post('http://127.0.0.1:8091/configure', {data: {writeEnabled: false}});
 expect(disabled.ok()).toBe(true);
 await page.reload();
 await expect(page.getByText('GPS operation: succeeded', {exact: true})).toBeVisible();
 await expect(page.getByText('Approved intended: 0, 12', {exact: true})).toBeVisible();
 expect((await fixtureState(page.request, account.key)).writes).toHaveLength(1);
 expect((await providerState(page.request)).requests.length).toBe(calls);
});
